"""empty message

Revision ID: 04a2a77e28ef
Revises: ef911e4fcfdc
Create Date: 2021-02-04 12:50:46.555886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a2a77e28ef'
down_revision = 'ef911e4fcfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todo_title_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todos_titles', ['todo_title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todo_title_id')
    op.drop_table('todos_titles')
    # ### end Alembic commands ###
