"""empty message

Revision ID: a0ca4e823ade
Revises: 04a2a77e28ef
Create Date: 2021-02-04 12:56:55.487752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ca4e823ade'
down_revision = '04a2a77e28ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
