"""empty message

Revision ID: ef911e4fcfdc
Revises: 
Create Date: 2021-01-28 12:01:29.668368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef911e4fcfdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # se ci sono dei dati presenti aggiungere una colonna con il vincolo NOT NULL  genererà un errore
    # quindi disattiviamo il comando sotto
    # op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # e lo modifichiamo inserendo true alla condizione nallable --> in sql NOT NULL
    # questo ci permette di aggiungere una colonna senza vincolo 
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # adesso diamo un comando di aggrionamento della tabella utilizzando il linguaggio sql
    # in modo da inserire un valore nelle celle vuote
    op.execute(' UPDATE todos SET completed=False WHERE completed IS NULL;')

    # una volta che la tabella è stata popolata possiamo aggiuungere il vincolo NOT NULL 
    # dato che nella nostra tabella vogliamo questo vincolo
    op.alter_column('todos','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
